# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hmlvaraus', '0010_hmlreservation_berth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('purchase_code', models.CharField(max_length=40, verbose_name='Purchase code')),
                ('reserver_name', models.CharField(blank=True, max_length=100, verbose_name='Reserver name')),
                ('reserver_email_address', models.EmailField(blank=True, max_length=254, verbose_name='Reserver email address')),
                ('reserver_phone_number', models.CharField(blank=True, max_length=30, verbose_name='Reserver phone number')),
                ('reserver_address_street', models.CharField(blank=True, max_length=100, verbose_name='Reserver address street')),
                ('reserver_address_zip', models.CharField(blank=True, max_length=30, verbose_name='Reserver address zip')),
                ('reserver_address_city', models.CharField(blank=True, max_length=100, verbose_name='Reserver address city')),
                ('vat_percent', models.IntegerField(choices=[0, 10, 14, 24], default=24)),
                ('price_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('purchase_process_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase process started')),
                ('purchase_process_success', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process success')),
                ('purchase_process_failure', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process failure')),
                ('purchase_process_notified', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('hml_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hmlvaraus.HMLReservation', verbose_name='HMLReservation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
