# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0011_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_process_report_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified'),
        ),
    ]
