# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0012_purchase_purchase_process_report_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_service_method',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_service_order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_service_paid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service paid'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_service_return_authcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reserver address street'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_service_timestamp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service timestamp'),
        ),
    ]
