# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0013_auto_20171129_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase finished'),
        ),
    ]
