# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-01 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0014_purchase_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='reserving',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reserving'),
        ),
    ]
