# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0015_berth_reserving'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='hmlvaraus.HMLReservation'),
        ),
        migrations.AddField(
            model_name='hmlreservation',
            name='renewal_code',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='Renewal code'),
        ),
    ]
