# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0016_auto_20171204_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='renewal_notification_day_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification day before end sent at'),
        ),
        migrations.AddField(
            model_name='hmlreservation',
            name='renewal_notification_month_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification month before end sent at'),
        ),
        migrations.AddField(
            model_name='hmlreservation',
            name='renewal_notification_week_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification week before end sent at'),
        ),
    ]
