# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0018_auto_20171218_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmlreservation',
            name='key_return_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Key return notification sent at'),
        ),
    ]
