# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-23 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0020_groundberthprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hmlreservation',
            name='berth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hml_reservations', to='hmlvaraus.Berth', verbose_name='Berth'),
        ),
        migrations.AlterField(
            model_name='hmlreservation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hml_reservation', to='resources.Reservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='hml_reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.SET_NULL, to='hmlvaraus.HMLReservation', verbose_name='HMLReservation'),
        ),
    ]
