# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0022_smsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='hml_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='hmlvaraus.HMLReservation', verbose_name='Reservation'),
        ),
    ]
