# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0023_auto_20180410_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='hml_reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmlvaraus.HMLReservation', verbose_name='HMLReservation'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vat_percent',
            field=models.IntegerField(choices=[(0, '0'), (10, '10'), (14, '24'), (24, '24')], default=24),
        ),
    ]
