# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-24 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hmlvaraus', '0024_auto_20180412_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='reserving_staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
